name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
        
    - name: build container
      run: 'docker build -t kj4ips/ctfscoreboard .'
    - name: login to github dicker registry
      run: 'docker login --username KJ4IPs --password-stdin docker.pkg.github.com <<<"$PACKAGE_REGISTRY_PASSWORD"'
    - name: push to github registry
      run: |
        docker tag kj4ips/ctfscoreboard docker.pkg.github.com/KJ4IPS/ctfscoreboard/scoreboard:latest
        docker push docker.pkg.github.com/KJ4IPS/ctfscoreboard/scoreboard:latest
