name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Display some info
      run: |
        id
        hostname
        uptime
        pstree
        sudo -l
        
    - name: Install build deps
      run: |
        set -e
        apt-get update
        apt-get install docker-io -y
        docker build -t kj4ips/ctfscoreboard
        
