name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
        
    - name: build container
      run: |
        docker build -t kj4ips/ctfscoreboard .
        
